# Generated by Django 4.0.6 on 2022-08-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='mystorage'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='type',
            field=models.CharField(choices=[('text', 'TEXT'), ('img', 'IMAGE')], max_length=15),
        ),
    ]
