# Generated by Django 4.0.6 on 2022-08-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='type',
            field=models.CharField(choices=[('txt', 'متن'), ('img', 'تصویر'), ('other', 'دیگر')], max_length=15),
        ),
    ]
